version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb+srv://kevinkumar0a2:gSofu73BFxv7wjrd@cluster0.moua0ds.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - FRONTEND_URL=https://shadowcracker.vercel.app/
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    restart: unless-stopped
    networks:
      - mynet

networks:
  mynet:
    driver: bridge 
