version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/shadowcracker
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    restart: unless-stopped
    networks:
      - shadowcracker-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=shadowcracker
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - shadowcracker-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - shadowcracker-network

volumes:
  mongo_data:

networks:
  shadowcracker-network:
    driver: bridge 